language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t supratim94336/react-fibonacci -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true supratim94336/react-fibonacci npm test

after_success:
    - docker build -t supratim94336/multi-client ./client
    - docker build -t supratim94336/multi-nginx ./nginx
    - docker build -t supratim94336/multi-server ./server
    - docker build -t supratim94336/multi-worker ./worker

    # login to docker cli with encrypted environment variables:
    # (this way you make ready the input of your first command 
    # which is after pipe)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take these images and push them to docker cli
    - docker push supratim94336/multi-client
    - docker push supratim94336/multi-nginx
    - docker push supratim94336/multi-server
    - docker push supratim94336/multi-worker

    deloy:
        edge: true
        provider: elasticbeanstalk
        region: us-west-2
        app: multi-docker
        env: MultiDocker-Env
        bucket_name: elasticbeanstalk-us-west-2-306476627547
        bucket_path: docker-multi
        on:
            branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: 
            secure: $AWS_SECRET_KEY
